### ISSUE TITLE
使用最新的0.3镜像登录报错

### ISSUE THREAD

**Issue by mjyhj** [NolanHzy/nvjdc#8]
用最早的0.3是没问题的，更新到最新的镜像后，反而出错了
![1](https://user-images.githubusercontent.com/22577418/140063965-746ed87c-b103-4145-9ca0-15b8e53e89e4.jpg)

日志：

```
1304288****安全验证
1304288****安全验证破解
验证失败
1304288****安全验证破解
验证失败
1304288****安全验证破解
验证成功
输入验证码659559
https://plogin.m.jd.com/login/login?appid=300&returnurl=https%3A%2F%2Fwq.jd.com%2Fpassport%2FLoginRedirect%3Fstate%3D2087738584%26returnurl%3Dhttps%253A%252F%252Fhome.m.jd.com%252FmyJd%252Fnewhome.action%253Fsceneval%253D2%2526ufc%253D%2526&source=wq_passport
PuppeteerSharp.EvaluationFailedException: Execution context was destroyed, most likely because of a navigation.
 ---> PuppeteerSharp.MessageException: Execution context was destroyed, most likely because of a navigation.
   at PuppeteerSharp.CDPSession.SendAsync(String method, Object args, Boolean waitForCallback) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\CDPSession.cs:line 166
   at PuppeteerSharp.CDPSession.SendAsync[T](String method, Object args) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\CDPSession.cs:line 118
   at PuppeteerSharp.ExecutionContext.ExecuteEvaluationAsync(String method, Object args) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\ExecutionContext.cs:line 182
   --- End of inner exception stack trace ---
   at PuppeteerSharp.ExecutionContext.ExecuteEvaluationAsync(String method, Object args) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\ExecutionContext.cs:line 182
   at PuppeteerSharp.ExecutionContext.RemoteObjectTaskToObject[T](Task`1 remote) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\ExecutionContext.cs:line 136
   at PuppeteerSharp.DOMWorld.EvaluateExpressionAsync[T](String script) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\DOMWorld.cs:line 88
   at Server.PageServer.PageServer.VerifyCode(Int32 qlkey, String Phone, String Code) in E:\03工作源码\NETJDC\Server\PageServer\PageServer.cs:line 300

```

**Comment by mjyhj** [comment]
DOCKER 运行了一段时候就这样，全部不能登录。
重启后就可以了，明天试试会不会复现
